import { encrypt } from './utils.js';

export const SAMPLE_PLAIN = [
  'WE HOLD THESE TRUTHS TO BE SELF EVIDENT THAT ALL MEN ARE CREATED EQUAL THAT THEY ARE ENDOWED BY THEIR CREATOR',
  'WITH CERTAIN UNALIENABLE RIGHTS THAT AMONG THESE ARE LIFE LIBERTY AND THE PURSUIT OF HAPPINESS THAT TO SECURE',
  'THESE RIGHTS GOVERNMENTS ARE INSTITUTED AMONG MEN DERIVING THEIR JUST POWERS FROM THE CONSENT OF THE GOVERNED',
  'THAT WHENEVER ANY FORM OF GOVERNMENT BECOMES DESTRUCTIVE OF THESE ENDS IT IS THE RIGHT OF THE PEOPLE TO ALTER',
  'OR TO ABOLISH IT AND TO INSTITUTE NEW GOVERNMENT LAYING ITS FOUNDATION ON SUCH PRINCIPLES AND ORGANIZING',
  'ITS POWERS IN SUCH FORM AS TO THEM SHALL SEEM MOST LIKELY TO EFFECT THEIR SAFETY AND HAPPINESS',
].join(' ');
export const SAMPLE_P2C = 'TZJFRQODACNBUSPLGYXHEKVMIW';
export const SAMPLE_CIPHER = encrypt(SAMPLE_PLAIN, SAMPLE_P2C);
export const SAMPLE_FIXED = { W: 'V', E: 'R', H: 'D', O: 'P', L: 'B', D: 'F', T: 'H', S: 'X' };
export const SHORT_SAMPLE_PLAIN = SAMPLE_PLAIN.split(' ').slice(0, 32).join(' ');
